# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="python311 py311-sqlite3 py311-pillow py311-numpy py311-lxml py311-webrtcvad py311-setuptools ffmpeg unrar unzip"
ARG UPSTREAM_URL="https://api.github.com/repos/morpheus65535/bazarr/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:6767/ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Bazarr" \
      org.opencontainers.image.description="Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you." \
      org.opencontainers.image.source="https://github.com/daemonless/bazarr" \
      org.opencontainers.image.url="https://www.bazarr.media/" \
      org.opencontainers.image.documentation="https://wiki.bazarr.media/" \
      org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Management" \
      io.daemonless.port="6767" \
      io.daemonless.volumes="/config,/movies,/tv" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download and install Bazarr
RUN BAZARR_VERSION=$(fetch -qo - "${UPSTREAM_URL}" | jq -r "${UPSTREAM_JQ}") && \
    mkdir -p /app && \
    fetch -qo /tmp/bazarr.zip "https://github.com/morpheus65535/bazarr/releases/download/${BAZARR_VERSION}/bazarr.zip" && \
    unzip -d /app /tmp/bazarr.zip && \
    rm /tmp/bazarr.zip && \
    echo "${BAZARR_VERSION}" > /app/version && \
    chown -R bsd:bsd /app

# Copy root filesystem
COPY root/ /

# Set permissions
RUN chmod +x /etc/services.d/bazarr/run /healthz /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 6767

# --- Volumes (Injected by Generator) ---
VOLUME /config /movies /tv